### ISSUE TITLE
fix: 关于主体模式的调整

### ISSUE THREAD

**Issue by Pleasurecruise** [pipijoe/xryder-web#4]
文档简介部分针对跟随系统的主题似乎有点问题

| 跟随系统主题显示 | 预期的暗色主题显示 |
|------------------|--------------------|
| ![跟随系统主体显示](https://github.com/user-attachments/assets/c19c0644-fc54-41c9-bb6e-a520c4a54625) | ![预期的暗色主体显示](https://github.com/user-attachments/assets/47bab57c-1bd1-43f1-a3aa-e565591028a6) |

**Comment by pipijoe** [comment]
@Pleasurecruise 谢谢提出问题，问题已修复。
